### ISSUE TITLE
Login pattern too restrictive

### ISSUE THREAD

**Issue by Illutax** [CollinAlpert/Tik#1]
https://github.com/CollinAlpert/Tik/blob/22e4d5aaec464b24acb281fad9b6dc1dccc324a6/src/main/resources/templates/login.html#L45

It doesn't allow for TLD like .co.uk or .hamburg

**Comment by luporr** [comment]
Don’t care. People who use .hamburg are gay.

**Comment by CollinAlpert** [comment]
Hi @Illutax, thanks for raising the issue. Are you actually trying to use this project? If so, I'd be happy to merge PRs you create.
